params:
  det_input_dim: 4
  track_input_dim: 8
  hidden_dim: 256
  dropout: 0.1
  track_encoder_n_heads: 8
  track_encoder_n_layers: 6
  track_encoder_ffn_dim: 512
  projector_intermediate_dim: 512
  logits_temperature_init: 0.07