defaults:
  - dancetrack_bbox.yaml

index:
  type: mot
  params:
    paths:
      - /media/home/data/BEE24

feature_extractor:
  extractor_params:
    prediction_path: /media/home/cameltrack-states/extracted-features-bee24


n_tracks: 150
clip_length: 50