defaults:
  - transform: scaled.yaml
  - augmentations: default.yaml
  - feature_extractor: pred_bbox.yaml

index:
  type: mot
  params:
    paths:
      - /media/home/DanceTrack-orig/

n_tracks: 40
clip_length: 30
min_clip_tracks: 1
clip_sampling_step: 1
val_clip_sampling_step: 1
