defaults:
  - dancetrack_bbox.yaml

index:
  type: mot
  params:
    paths:
      - /media/home/SoccerNet

feature_extractor:
  extractor_params:
    prediction_path: /media/home/cameltrack-states/extracted-features-soccernet

n_tracks: 25
clip_length: 150