_target_: mot_jepa.datasets.dataset.augmentations.base.CompositionAugmentation
augmentations:
  - _target_: mot_jepa.datasets.dataset.augmentations.bbox.BBoxGaussianNoiseAugmentation
    proba: 0.5
    sigma: 0.05
    unobs_noise: true
  - _target_: mot_jepa.datasets.dataset.augmentations.video.OcclusionAugmentations
    drop_ratio: 0.5
  - _target_: mot_jepa.datasets.dataset.augmentations.video.IdentitySwitchAugmentation
    switch_ratio: 0.3

