_target_: mot_jepa.datasets.dataset.augmentations.base.CompositionAugmentation
augmentations:
  - _target_: mot_jepa.datasets.dataset.augmentations.bbox.BBoxGaussianNoiseAugmentation
    sigma: 0.05
    proba: 0.40
    unobs_noise: True
  - _target_: mot_jepa.datasets.dataset.augmentations.bbox.BBoxGaussianNoiseAugmentation
    sigma: 0.10
    proba: 0.10
    unobs_noise: True
  - _target_: mot_jepa.datasets.dataset.augmentations.bbox.BBoxGaussianNoiseAugmentation
    sigma: 0.25
    proba: 0.05
    unobs_noise: True
  - _target_: mot_jepa.datasets.dataset.augmentations.video.PointOcclusionAugmentations
    drop_ratio: 0.3
  - _target_: mot_jepa.datasets.dataset.augmentations.video.LeftOrRightOcclusionAugmentations
    drop_ratio: 0.2
  - _target_: mot_jepa.datasets.dataset.augmentations.video.IdentitySwitchAugmentation
    switch_ratio: 0.3
  - _target_: mot_jepa.datasets.dataset.augmentations.appearance.AppearanceNoiseAugmentation
    alpha: 0.5
  - _target_: mot_jepa.datasets.dataset.augmentations.video.MaskFeatureAugmentation
    drop_ratios:
      appearance: 0.4
      bbox: 0.1
      keypoints: 0.1

