_target_: mot_jepa.datasets.dataset.augmentation.base.CompositionAugmentation
augmentations:
  - _target_: mot_jepa.datasets.dataset.augmentation.bbox.BBoxGaussianNoiseAugmentation
    proba: 0.5
    sigma: 0.05
    unobs_noise: true
  - _target_: mot_jepa.datasets.dataset.augmentation.video.OcclusionAugmentations
    drop_ratio: 0.5
  - _target_: mot_jepa.datasets.dataset.augmentation.video.IdentitySwitchAugmentation
    switch_proba: 0.3

