defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack_bbox.yaml
  - train: batch.yaml
  - eval: default.yaml
  - model_config: mm_bboxes.yaml
  - path: default.yaml

experiment_name: exp64b-fromExp63-4Layers
dataset_name: DanceTrack
