defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack_bbox.yaml
  - train: bce.yaml
  - eval: default.yaml
  - model_config: mm_tdsp_bboxes.yaml
  - path: default.yaml

experiment_name: exp108b-fromExp107-BboxEmbDim512
dataset_name: DanceTrack
