defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: sportsmot_bbox.yaml
  - train: bce.yaml
  - eval: default.yaml
  - model_config: mm_tdsp_bboxes.yaml
  - path: default.yaml

experiment_name: exp04b-fromExp03-Mem150
dataset_name: SportsMOT

resources:
  batch_size: 16
