defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: mm.yaml
  - eval: default.yaml
  - model_config: mm_bboxes_keypoints_appearance.yaml
  - path: default.yaml

experiment_name: exp68-fromExp67-WeightDecay
dataset_name: DanceTrack
