defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: sportsmot.yaml
  - train: bce.yaml
  - eval: default.yaml
  - model_config: mm_tdsp_bboxes_keypoints_appearance.yaml
  - path: default.yaml

experiment_name: exp04-fromExp03-Mem150
dataset_name: SportsMOT

resources:
  batch_size: 8

train:
  max_epochs: 10

  optimizer_config:
    _target_: torch.optim.AdamW
    lr: 1e-5
    weight_decay: 1e-3

  scheduler_config:
    _target_: mot_jepa.trainer.scheduler.create_warmup_cosine_annealing_scheduler
    n_warmup_epochs: 1
