defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model_config: mm_bboxes_keypoints_appearance.yaml
  - path: default.yaml

experiment_name: exp39-fromExp38-AddFeatureDropoutAugmentation
dataset_name: DanceTrack
