defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model_config: with_interaction_encoder.yaml
  - path: default.yaml

experiment_name: exp12-fromExp10-StrongerBBoxJitter
dataset_name: DanceTrack
