defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model: default.yaml
  - path: default.yaml

experiment_name: exp11-TripletLoss-InfoNCE+MSELoss-StrongDetectionEncoder-XYXY-BatchLoss-ReproduceLoss
dataset_name: DanceTrack
