defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model_config: mm_bboxes_keypoints.yaml
  - path: default.yaml

experiment_name: exp28-fromExp26-IgnorePerKeypointConfidence
dataset_name: DanceTrack
