defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model: default.yaml
  - path: default.yaml

experiment_name: exp01-Baseline-BatchLevelInfoNCE
dataset_name: DanceTrack
