defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: default.yaml
  - eval: default.yaml
  - model_config: default.yaml
  - path: default.yaml

experiment_name: exp04-fromExp01-MaxTracks40
dataset_name: DanceTrack
