defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack_keypoints.yaml
  - train: bce.yaml
  - eval: default.yaml
  - model_config: mm_tdsp_keypoints.yaml
  - path: default.yaml

experiment_name: exp108k-fromExp107-BboxEmbDim512
dataset_name: DanceTrack
