_target_: mot_jepa.datasets.dataset.transform.ComposeTransform
transforms:
  - _target_: mot_jepa.datasets.dataset.transform.BBoxXYWHtoXYXY
  - _target_: mot_jepa.datasets.dataset.transform.FeatureStandardization
    coord_mean:
      bbox: [0.5, 0.5, 0.5, 0.5, 0.5]
    coord_std:
      bbox: [0.2, 0.1, 0.2, 0.1, 1.0]