_target_: tdlp.datasets.dataset.transform.ComposeTransform
transforms:
  - _target_: tdlp.datasets.dataset.transform.BBoxXYWHtoXYXY
  - _target_: tdlp.datasets.dataset.transform.BBoxMinMaxScaling
  - _target_: tdlp.datasets.dataset.transform.FeatureFODStandardization
    coord_mean:
      bbox: [0.5, 0.5, 0.5, 0.5, 0.5]
    coord_std:
      bbox: [0.1, 0.1, 0.1, 0.1, 1.0]
    fod_mean:
      bbox: [0.0, 0.0, 0.0, 0.0, 0.0]
    fod_std:
      bbox: [0.05, 0.05, 0.05, 0.05, 1.0]
    fod_time_scaled: true