extractor_type: pred_bbox
extractor_params:
  prediction_path: /media/home/cameltrack-states/extracted-features
  extra_false_positives: true
  feature_names:
    - appearance

  random_appearance_jitter_ratio: 0.0
  random_appearance_jitter_range: 0