max_epochs: 10
gradient_clip: null
mixed_precision: true

loss_config:
  _target_: mot_jepa.trainer.losses.infonce.IDLevelInfoNCE

optimizer_config:
  _target_: torch.optim.AdamW
  lr: 1e-4

scheduler_config:
  _target_: mot_jepa.trainer.scheduler.create_warmup_cosine_annealing_scheduler
  n_warmup_epochs: 1
