defaults:
  - base.yaml
  - _self_

loss_config:
  _target_: mot_jepa.trainer.losses.infonce.MultiFeatureLoss
  mm_loss:
    _target_: mot_jepa.trainer.losses.infonce.IDLevelInfoNCE
  per_feature_losses:
    bbox:
      _target_: mot_jepa.trainer.losses.infonce.BatchLevelInfoNCE
    keypoints:
      _target_: mot_jepa.trainer.losses.infonce.BatchLevelInfoNCE
    appearance:
      _target_: mot_jepa.trainer.losses.infonce.IDLevelInfoNCE
  per_feature_weights:
    bbox: 0.3
    keypoints: 0.3
    appearance: 0.3
