_target_: mot_jepa.architectures.tdcp.core.build_mm_tdcp_model
mm_dim: 1024
common_params:
  hidden_dim: 256
  dropout: 0.1
  track_encoder_n_heads: 8
  track_encoder_n_layers: 2
  track_encoder_ffn_dim: 512
  projector_intermediate_dim: 512
  interaction_encoder_enable: false
  interaction_encoder_n_heads: 8
  interaction_encoder_n_layers: 2
  interaction_encoder_ffn_dim: 512
per_feature_params:
  bbox:
    feature_encoder_type: motion
    feature_encoder_params:
      input_dim: 5
  keypoints:
    feature_encoder_type: motion
    feature_encoder_params:
      input_dim: 35
  appearance:
    hidden_dim: 512
    feature_encoder_type: parts_appearance
    feature_encoder_params:
      emb_size: 128
      hidden_dim: 512
    track_encoder_enable_motion_encoder: false
aggregator_type: transformer
aggregator_params:
  hidden_dim: ${model_config.mm_dim}
  n_heads: 8
  n_layers: 2
  dropout: 0.1

per_feature_checkpoint:
  bbox: /media/home/MOT-JEPA-outputs/experiments/DanceTrack/exp93b-fromExp90-ClipLevelBCE/checkpoints/last.pt
  keypoints: /media/home/MOT-JEPA-outputs/experiments/DanceTrack/exp93k-fromExp90-ClipLevelBCE/checkpoints/last.pt
  appearance: /media/home/MOT-JEPA-outputs/experiments/DanceTrack/exp98a-fromExp97-EmbDim512/checkpoints/last.pt

object_interaction_encoder_enable: true
object_interaction_encoder_params:
  hidden_dim: ${model_config.mm_dim}
  n_heads: 8
  n_layers: 2
  dropout: 0.1