_target_: mot_jepa.architectures.tdcp.core.build_mm_tdcp_model
mm_dim: 256
common_params:
  hidden_dim: 256
  dropout: 0.1
  track_encoder_n_heads: 8
  track_encoder_n_layers: 2
  track_encoder_ffn_dim: 512
  projector_intermediate_dim: 512
  interaction_encoder_enable: false
  interaction_encoder_n_heads: 8
  interaction_encoder_n_layers: 2
  interaction_encoder_ffn_dim: 512
per_feature_params:
  bbox:
    feature_encoder_type: motion
    feature_encoder_params:
      input_dim: 5
aggregator_type: sum
aggregator_params: {}
