_target_: mot_jepa.architectures.tdcp.core.build_mm_tdcp_model
common_params:
  hidden_dim: 256
  dropout: 0.1
  track_encoder_n_heads: 8
  track_encoder_n_layers: 2
  track_encoder_ffn_dim: 512
  projector_intermediate_dim: 512
  interaction_encoder_enable: true
  interaction_encoder_n_heads: 8
  interaction_encoder_n_layers: 2
  interaction_encoder_ffn_dim: 512
per_feature_params:
  bbox:
    input_dim: 5
  keypoints:
    input_dim: 35
aggregator_type: sum
aggregator_params: {}